//start

String Integrantes() {
	String HTML = "";

	HTML += "<!DOCTYPE html>";
	HTML += "<html lang=\"pt-br\">";
	HTML += "<head>";
	HTML += "    <meta charset=\"UTF-8\">";
	HTML += "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">";
	HTML += "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">";
	HTML += "    <title>Integrantes</title>";
	HTML += "    <link rel=\"shortcut icon\" href=\"/nosso-grupo-dev/media/studentsico.ico\" type=\"image/x-icon\">";
	HTML += "    <style>";
	HTML += "        * {";
	HTML += "            margin: 0;";
	HTML += "            padding: 0;";
	HTML += "            box-sizing: border-box;";
	HTML += "        }";
	HTML += "        body {";
	HTML += "            background-image: linear-gradient(to bottom, #03A64A, #025940);";
	HTML += "            margin: 0;";
	HTML += "}";
	HTML += "        nav{";
	HTML += "            padding-left: 30px;";
	HTML += "            padding-right: 30px;";
	HTML += "            margin: 20px;";
	HTML += "            height: 130px;";
	HTML += "            background-color: white;";
	HTML += "            display: flex;";
	HTML += "            justify-content: space-between;";
	HTML += "            align-items: center;";
	HTML += "            border-radius: 20px;";
	HTML += "            box-shadow: 3px 2px 7px black;";
	HTML += "        }";
	HTML += "        .navimg {";
	HTML += "            width: 150px;";
	HTML += "            height: auto;";
	HTML += "            margin-left: 15px;";
	HTML += "        }";
	HTML += "        .navlink {";
	HTML += "            color: black;";
	HTML += "            font-size: 22px;";
	HTML += "            text-decoration: none;";
	HTML += "            margin: 15px;";
	HTML += "        }";
	HTML += "        .AreaImages {";
	HTML += "            margin: 80px;";
	HTML += "            display: flex;";
	HTML += "        }";
	HTML += "        .ImagesIntegrantes {";
	HTML += "            width: 200px;";
	HTML += "            border-radius: 10%;";
	HTML += "            box-shadow: 2px 1px 7px black;";
	HTML += "        }";
	HTML += "        p {";
	HTML += "            font-size: 20px;";
	HTML += "            font-family: 'Noto Sans', sans-serif;";
	HTML += "            color: white;";
	HTML += "            margin-left: 100px;";
	HTML += "            margin-top: 100px;";
	HTML += "        }";
	HTML += "    </style>";
	HTML += "</head>";
	HTML += "<body>";
	HTML += "    <nav>";
	HTML += "        <a href=\"./site.html\" class=\"navlink\">Voltar</a>";
	HTML += "        <img class=\"navimg\" src=\"https://raw.githubusercontent.com/OwseiWasTaken/nosso-grupo/dev/media/locust.png\"";
	HTML += "            alt=\"locust\">";
	HTML += "    </nav>";
	HTML += "    <div class=\"AreaImages\">";
	HTML += "        <img class=\"ImagesIntegrantes\"";
	HTML += "            src=\"https://github.com/OwseiWasTaken/nosso-grupo/blob/dev/media/Miguel.jpeg?raw=true\" alt=\"Miguel\">";
	HTML += "        <p>Miguel, 16 anos - MED 6</p>";
	HTML += "    </div>";
	HTML += "    <div class=\"AreaImages\">";
	HTML += "        <img class=\"ImagesIntegrantes\"";
	HTML += "            src=\"https://github.com/OwseiWasTaken/nosso-grupo/blob/dev/media/Enzo.jpeg?raw=true\" alt=\"Enzo\">";
	HTML += "        <p>Enzo, 16 anos - MED 6</p>";
	HTML += "    </div>";
	HTML += "    <div class=\"AreaImages\">";
	HTML += "        <img class=\"ImagesIntegrantes\"";
	HTML += "            src=\"https://github.com/OwseiWasTaken/nosso-grupo/blob/dev/media/Manse.jpeg?raw=true\" alt=\"Manse\">";
	HTML += "        <p>Manse, 16 anos - MED 6</p>";
	HTML += "    </div>";
	HTML += "    <div class=\"AreaImages\">";
	HTML += "        <img class=\"ImagesIntegrantes\"";
	HTML += "            src=\"https://github.com/OwseiWasTaken/nosso-grupo/blob/dev/media/Gustavo.jpeg?raw=true\" alt=\"Gustavo\">";
	HTML += "        <p>Gustavo, 17 anos - MED 6</p>";
	HTML += "    </div>";
	HTML += "    <div class=\"AreaImages\">";
	HTML += "        <img class=\"ImagesIntegrantes\"";
	HTML += "            src=\"https://github.com/OwseiWasTaken/nosso-grupo/blob/dev/media/gabriel.jpeg?raw=true\" alt=\"Gabriel G\">";
	HTML += "        <p>Gabriel Gomes, 17 anos - MED 6 </p>";
	HTML += "    </div>";
	HTML += "    <div class=\"AreaImages\">";
	HTML += "        <img class=\"ImagesIntegrantes\" src=\"https://github.com/OwseiWasTaken/nosso-grupo/blob/dev/media/BIEL%20n.jpeg?raw=true\" alt=\"Nogueira\">";
	HTML += "        <p>Gabriel Nogueira, 16 anos - MED 6</p>";
	HTML += "    </div>";
	HTML += "    <div class=\"AreaImages\">";
	HTML += "        <img class=\"ImagesIntegrantes\" src=\"https://github.com/OwseiWasTaken/nosso-grupo/blob/dev/media/sampaio.jpeg?raw=true\" alt=\"Sampaio\">";
	HTML += "        <p>Sampaio, 16 anos - MED 6</p>";
	HTML += "    </div>";
	HTML += "</body>";
	HTML += "</html>";
}

String site(){

	String HTML = "";

	HTML += "<!DOCTYPE html>";
	HTML += "<html lang=\"pt-br\">";
	HTML += "<head>";
	HTML += "	<meta charset=\"UTF-8\">";
	HTML += "	<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">";
	HTML += "	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">";
	HTML += "	<title>Locust</title>";
	HTML += "	<link rel=\"shortcut icon\" href=\"media/favicon.ico\">";
	HTML += "	<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">";
	HTML += "	<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>";
	HTML += "	<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans&display=swap\" rel=\"stylesheet\">";
	HTML += "	<style>";
	HTML += "		body {";
	HTML += "			background-image: linear-gradient(to bottom, #03A64A, #025940);";
	HTML += "			margin: 0;";
	HTML += "		}";
	HTML += "		nav {";
	HTML += "			padding-left: 30px;";
	HTML += "			padding-right: 30px;";
	HTML += "			margin: 20px;";
	HTML += "			height: 130px;";
	HTML += "			background-color: white;";
	HTML += "			display: flex;";
	HTML += "			justify-content: space-between;";
	HTML += "			align-items: center;";
	HTML += "			border-radius: 20px;";
	HTML += "			box-shadow: 3px 2px 7px black;";
	HTML += "		}";
	HTML += "		.navimg {";
	HTML += "			width: 150px;";
	HTML += "			height: auto;";
	HTML += "			margin-left: 15px;";
	HTML += "		}";
	HTML += "		.navlink {";
	HTML += "			color: black;";
	HTML += "			font-size: 22px;";
	HTML += "			text-decoration: none;";
	HTML += "			margin: 15px;";
	HTML += "		}";
	HTML += "		#img {";
	HTML += "			text-align: center;";
	HTML += "		}";
	HTML += "		.centerimg {";
	HTML += "			width: 350px;";
	HTML += "			border-radius: 20px;";
	HTML += "			margin: 40px;";
	HTML += "			box-shadow: 3px 3px 8px black;";
	HTML += "			background-color: white;";
	HTML += "		}";
	HTML += "		a {";
	HTML += "			font-family: 'Noto Sans', sans-serif;";
	HTML += "		}";
	HTML += "		#center {";
	HTML += "			margin-bottom: 150px;";
	HTML += "		}";
	HTML += "		#area-conteudo {";
	HTML += "			padding: 60px;";
	HTML += "		}";
	HTML += "		#titulo-principal {";
	HTML += "			color: #022424;";
	HTML += "			font-family: 'Noto Sans', sans-serif;";
	HTML += "			text-align: center;";
	HTML += "			font-size: 30px;";
	HTML += "			padding: 30px;";
	HTML += "		}";
	HTML += "		.subtitulos {";
	HTML += "			color: #022424;";
	HTML += "			font-family: 'Noto Sans', sans-serif;";
	HTML += "			font-size: 20px;";
	HTML += "			padding: 25px;";
	HTML += "		}";
	HTML += "		ul{";
	HTML += "			padding-left: 70px;";
	HTML += "		}";
	HTML += "		p{";
	HTML += "			font-size: 20px;";
	HTML += "			font-family: 'Noto Sans', sans-serif;";
	HTML += "			color:white;";
	HTML += "			text-indent: 20px;";
	HTML += "		}";
	HTML += "		ol{";
	HTML += "			margin: 25px;";
	HTML += "			padding-left: 50px;";
	HTML += "			color: white;";
	HTML += "			list-style-type: circle;";
	HTML += "			font-family: 'Noto Sans', sans-serif;";
	HTML += "			";
	HTML += "		}";
	HTML += "	</style>";
	HTML += "</head>";
	HTML += "<body>";
	HTML += "	<nav class=\"navegation\">";
	HTML += "		<a href=\"#area-conteudo\" class=\"navlink\" >Conteúdo</a>";
	HTML += "		<img class=\"navimg\" src=\"https://raw.githubusercontent.com/OwseiWasTaken/nosso-grupo/dev/media/locust.png\"";
	HTML += "			alt=\"locust\">";
	HTML += "		<a class=\"navlink\" href=\"./integrantes.html\">Integrantes</a>";
	HTML += "	</nav>";
	HTML += "	<div id=\"img\">";
	HTML += "		<figure id=\"center\">";
	HTML += "			<img class=\"centerimg\"";
	HTML += "				src=\"https://raw.githubusercontent.com/OwseiWasTaken/nosso-grupo/dev/media/icones-de-localisation-de-la-carte-verte.png\"";
	HTML += "				alt=\"conectado\">";
	HTML += "		</figure>";
	HTML += "	</div>";
	HTML += "	<div id=\"area-conteudo\">";
	HTML += "		<h1 id=\"titulo-principal\">Conteúdo</h1>";
	HTML += "		<h2 class=\"subtitulos\">Nome do projeto</h2>";
	HTML += "		<ul>";
	HTML += "			<p>Locust</p>";
	HTML += "		</ul>";
	HTML += "		<h2 class=\"subtitulos\">Tipo do projeto</h2>";
	HTML += "		<ul>";
	HTML += "			<p>O objetivo do nosso projeto é criar um gerenciador de redes (Hardware e Software), sendo o produto final um dispositivo que se conecta com a rede do cliente o possibilitando controlar as saídas e entradas da sua internet, gerenciar IP, gerenciar fluxo. Também é código aberto, possui uma interface Arduino que disponibiliza a instalação de diversos sensores e módulos como GPS. ";
	HTML += "			</p>";
	HTML += "		</ul>";
	HTML += "		<h2 class=\"subtitulos\">Justificativa</h2>";
	HTML += "		<ul>";
	HTML += "			<p>A ideia do nosso projeto surgiu atráves de duas aulas no começo do ano de Matemática e FTP. Primeiramente foi quando a Joyce deu uma aula sobre GPS e passou um video que explicava a funcionalidade e isso foi o suficiente para surgir o interesse em fazer um projeto sobre isso, e quando o Saulo mostrou o Packet Tracer para nós achamos muito interessante a facilidade com que era possível configurar e conectar os dispositivos. Então resolvemos juntar esses dois temas para fazer o nosso projeto. </p>";
	HTML += "		</ul>";
	HTML += "		<h2 class=\"subtitulos\">Objetivo</h2>";
	HTML += "		<ul>";
	HTML += "			<p>O nosso objetivo é facilitar o gerenciamento de redes, principalmente LAN residencial e empresarial.</p>";
	HTML += "		</ul>";
	HTML += "		<h2 class=\"subtitulos\">Organização</h2>";
	HTML += "		<ul>";
	HTML += "			<p>Ensino Médio Técnico do Senac – Unidade Lapa Tito – Disciplina de Projeto Profissional - MED 6.</p>";
	HTML += "		</ul>";
	HTML += "		<h2 class=\"subtitulos\">Materiais e Custo</h2>";
	HTML += "		<ul>";
	HTML += "			<p>Em nosso proejeto utilizamos os seguintes Materiais com os seus respectivos preços:";
	HTML += "				<ol>";
	HTML += "					<li>Arduino = R$60,00</li>";
	HTML += "				</ol>";
	HTML += "				<ol>";
	HTML += "					<li>Peças eletrônicas = R$120,00</li>";
	HTML += "				</ol>";
	HTML += "				<ol>";
	HTML += "					<li>Mão de Obra = R$150,00</li>";
	HTML += "				</ol>";
	HTML += "			</p>";
	HTML += "		</ul>";
	HTML += "	</div>";
	HTML += "</body>";
	HTML += "</html>";

	return HTML;
}

//end
